### ISSUE TITLE
Views and Downloads cannnot be show in Production Search View because of different EventData in production

### ISSUE THREAD

**Issue by kjgarza** [datacite/lagottino#25]
Views and Downloads cannot be show in Production Search View because of different EventData in production. currently we have two different version of eventData. Version (A) its working in *production * this is the version it was running back in Novmember. Version (B) its in *stage*, this version includes all the new `camelCases` changes in metadata and the functionality to bring events from different dois (aka find_by_ids https://github.com/datacite/lagottino/commit/84efc46f5c9d14742c8daf23033f56a4ca00b27a
).  Version (B) are breaking changes. Needs API versioning.

child https://github.com/crosscite/doi-metadata-search/issues/89

*Proposed solutions*
A) Implement API versioning for breaking changes.
B) Enable search to accept both APIs 

We need to discuss advantages and disadvantages.

**Comment by mfenner** [comment]
I will be implementing API versioning in the `/events` API endpoint before the end of February, as this is also needed for PID Graph. This shouldn't delay the release of usage stats display to production search. Will be tracked via #26.

**Comment by mfenner** [comment]
API versioning has been implemented via #26.

**Comment by kjgarza** [comment]
changes to use EventData version 2 were done in https://github.com/crosscite/doi-metadata-search/commit/56ca45befb5c7baf4e25fc2ebf45caf03a747d94
