### ISSUE TITLE
Event Data documentation for citations

### ISSUE THREAD

**Issue by kjgarza** [datacite/lagottino#6]

**Comment by kjgarza** [comment]
EventData Query API Doc
https://dash.readme.io/project/datacite/v1.1/docs/eventdata-query-api-guide
https://dash.readme.io/project/datacite/v1.1/docs/eventdata-query-api-for-usage

**Comment by kjgarza** [comment]
please review @daslerr @pcruse

**Comment by mfenner** [comment]
I provided my feedback, making some small edits in readme.io.
