### ISSUE TITLE
Delete events stragy for reports

### ISSUE THREAD

**Issue by kjgarza** [datacite/lagottino#7]
child datacite/sashimi#30

**Comment by mfenner** [comment]
@kjgarza can you explain?

**Comment by kjgarza** [comment]
What happens with usage events when the corresponding usage report gets deleted? This is what would happen when we do API-endpoints-Consolidation for usage-reports, because usage-events use the UUID of the report as unique part of event, and the API-endpoints-Consolidation will modify the the UUID of the reports. Effectively the report will be updated but from the point of view of EventData it doesn't exist anymore. How are we dealing with this? This is issue about.

connected datacite/sashimi#22
child datacite/sashimi#30

**Comment by kjgarza** [comment]
connected datacite/lagottino#9

**Comment by kjgarza** [comment]
delete all events and ask CDL to update/re-sent the report
